services:
  app:
    build: ./
    image: alexandermorozzov/transport_frames:0.1.1
    env_file:
      - .env
    volumes:
      - ./:/usr/app/
    platform: linux/amd64
    ports:
      - 8000:8000

# services:
#   app:
#     build: ./
#     image: alexandermorozzov/transport_frames:0.1.1
#     env_file:
#       - .env
#     volumes:
#       - ./app:/app  # Corrected volume path
#       - ./requirements.txt:/app/requirements.txt
#     # platform: linux/amd64
#     ports:
#       - 8000:8000

# services:
#   web:
#     build: .
#     ports:
#       - 5000:5000
#     env_file:
#       - .env
#     environment:
#       - APP_NAME=transportframes_api
#       - APP_VERSION=dev
#     volumes:
#       - ./app:/app/app
#       - ./requirements.txt:/app/requirements.txt
#     command: /start-reload.sh